crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from leads.views import LandingPageView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing_page"),
    path('leads/', include('leads.urls', namespace="leads")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    leads_list, leads_detail, leads_create, leads_update, leads_delete, 
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, SignUpView
    )
app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='leads_list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='leads_detail'),
    path('create/', LeadCreateView.as_view(), name='leads_create'),
    path('update/<int:pk>', LeadUpdateView.as_view(), name='leads_update'),
    path('delete/<int:pk>', LeadDeleteView.as_view(), name='leads_delete'),
    path('signup/', SignUpView.as_view(), name='signup')
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    user = models.OneToOneField("User", on_delete=models.CASCADE)

    def __str__(self):
        if self.user.email:
            return self.user.email
        return f"{self.user.username}"
    

leads/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.forms import fields
from .models import Lead
from django.contrib.auth import get_user_model

User = get_user_model()


# This is a general type of form
class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


# This if model form

class LeadModelForm(forms.ModelForm):
    
    class Meta:
        model = Lead
        fields = ("first_name", "last_name", "age", "agent")



class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ("username",)
        fields_classes = {'username': UsernameField}

        

leads/views.py
from django.shortcuts import render, redirect, reverse
from django.views import generic
from django.http import HttpResponse
from .models import Lead, Agent
from .forms import LeadForm, LeadModelForm, CustomUserCreationForm
from django.conf import settings
from django.core.mail import send_mail


# Create your views here.


###################### class based views demonstration starts here ##################

class SignUpView(generic.CreateView):
    template_name = 'leads/leads_signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse('login')

    # def get_context_data(self, **kwargs):
    #     context = super(SignUpView, self).get_context_data(**kwargs)
    #     context['user_create'] = context['form']
    #     return context


class LandingPageView(generic.TemplateView):
    template_name = "landing_page.html"


class LeadListView(generic.ListView):
    queryset = Lead.objects.all()
    # model = Lead
    template_name = "leads/leads_list.html"
    # default context object passed is "object_list" --to override this
    context_object_name = 'leads'


def leads_list(request):
    '''
        returns all the lead
    '''
    leads = Lead.objects.all()
    context = {
        'leads': leads
    }

    return render(request, "leads/leads_list.html", context=context)


class LeadDetailView(generic.DetailView):
    queryset = Lead.objects.all()
    context_object_name = "lead"
    template_name = "leads/leads_detail.html"


def leads_detail(request, pk):
    '''
        returns lead with respect to pk
    '''
    lead = Lead.objects.get(id=pk)
    context = {
        'lead': lead
    }
    return render(request, 'leads/leads_detail.html', context=context)


# using forms.Form

# def leads_create(request):
#     '''
#         creates lead    
#     '''
#     form = LeadForm()
#     agent = Agent.objects.first()
#     if request.method == "POST":
#         form = LeadForm(request.POST)

#         if form.is_valid():
#             cleaned_data = form.cleaned_data
#             print(cleaned_data)
#             Lead.objects.create(
#                 first_name = cleaned_data['first_name'],
#                 last_name = cleaned_data['last_name'],
#                 age = cleaned_data['age'],
#                 agent = agent
#             )
#             return redirect('leads:leads_list')

#     context = {
#         'form': form
#     }
#     return render(request, 'leads/leads_create.html', context)

#   using forms.ModelForm


class LeadCreateView(generic.CreateView):
    form_class = LeadModelForm
    template_name = "leads/leads_create.html"

    def get_success_url(self):
        return reverse("leads:leads_list")

    def form_valid(self, form):
        send_mail(
            "Test message from gmail",
            str(form.cleaned_data),
            settings.EMAIL_HOST_USER,
            ['c0824340@mylambton.ca']
        )
        return super(LeadCreateView, self).form_valid(form)


def leads_create(request):
    '''
        creates lead    
    '''
    form = LeadModelForm()
    if request.method == "POST":
        form = LeadModelForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('leads:leads_list')

    context = {
        'form': form
    }
    return render(request, 'leads/leads_create.html', context)


class LeadUpdateView(generic.UpdateView):
    template_name = "leads/leads_update.html"
    queryset = Lead.objects.all()
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:leads_list")


def leads_update(request, pk):
    '''
        updates lead
    '''
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        form = LeadModelForm(instance=lead, data=request.POST)

        if form.is_valid():
            form.save()
            return redirect('leads:leads_list')

    context = {
        'form': form,
        'lead': lead
    }
    return render(request, 'leads/leads_update.html', context)


class LeadDeleteView(generic.DeleteView):
    template_name = 'leads/leads_delete.html'
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse("leads:leads_list")


def leads_delete(request, pk):
    '''
        deletes a record
    '''
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('leads:leads_list')

leads/templates/leads/leads_create.html
{% extends 'base_generic.html' %}

{% block title %}
    Create Lead
{% endblock %}

{% block body %}
    <h1> Create New Lead </h1>
    <hr />
    <form method="post" action='.'>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" value="submit">Submit </button>
    </form>
    <hr />
{% endblock %}

leads/templates/leads/leads_delete.html
{% extends 'base_generic.html' %}

{% block title %}
    Delete Lead
{% endblock %}

{% block content %}
    <h1> Are you sure you want to delete Lead? </h1>
    <hr />
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" value="submit">Submit </button>
    </form>
    <hr />
{% endblock %}

leads/templates/leads/leads_detail.html
{% extends 'base_generic.html' %}

{% block title %}
    Leads Detail
{% endblock %}


{% block head_css %}
    <style>
        .lead-detail {
            padding: 10px 5px;
            margin: 10px 5px;
            background: #f6f6f6;
        }
    </style>
{% endblock %}

{% block content %}
    <a href="{% url 'leads:leads_list' %}"> Go to Lead List </a>
    <hr />
    <div class="lead-detail">
        <h3> Name: {{ lead.first_name }} {{ lead.last_name }} </h3>
        <h4> Age: {{ lead.age }} </h4>
        <h5> Agent: {{ lead.agent }} </h5>
        <a href="{% url 'leads:leads_update' pk=lead.id %}"> Update informations </a>
        <br />
        <a href="{% url 'leads:leads_delete' pk=lead.id %}"> Delete Lead </a>
    </div>
{% endblock %}

leads/templates/leads/leads_list.html
{% extends 'base_generic.html' %}
{% block title %}
    Leads list
{% endblock %}

{% block head_css %}
    <style>
        .lead-list {
            padding: 10px 5px;
            margin: 10px 5px;
            background: #f6f6f6;
            width: 100%;
        }
    </style>

{% endblock %}

{% block content %}
    <h2> List of Leads </h2>
    <a href="{% url 'leads:leads_create' %}"> Create Leads</a>
    <hr />
    {% for lead in leads %}
        <div class = "lead-list">
            <a href="{% url 'leads:leads_detail' pk=lead.id %}">{{ lead.first_name }} {{ lead.last_name }}</a>
        </div>
    {% endfor %}
{% endblock %}

leads/templates/leads/leads_signup.html
{% extends 'base_generic.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit'> Signup </button>
    </form>
{% endblock content %}

leads/templates/leads/leads_update.html
{% extends 'base_generic.html' %}

{% block title %}
    Update Lead
{% endblock %}

{% block content %}
    <a href="{% url 'leads:leads_list' %}"> Go to Lead List </a>
    <hr />
    <h1> Update Lead {{lead.first_name}} {{lead.last_name}} </h1>
    <hr />
    <form method="post" action=''>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" value="submit">Submit </button>
    </form>
    <hr />
{% endblock %}

templates/base_generic.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %} {% endblock %}
        </title>
            {% block head_css %}
            {% endblock %}
        <link href="{% static 'leads/css/index.css' %}" rel="stylesheet" />
        <script src="{% static 'leads/scripts/index.js'%}"></script>

    </head>
    <body>
        {% include 'base_header.html' %}
        <div class="container">
            {% block content %}

            {% endblock content %}
        </div>
    </body>
</html>

templates/base_header.html
{% block content %}
    <div class="head-bar">
    {% if request.user.is_authenticated %}
        Logged in as: {{ request.user.username }}
        <a href="{% url 'logout' %}"> Logout </a>
    {% else %}
        <a href="{% url 'login' %}"> Login </a>
        <a href="{% url 'leads:signup' %}"> Signup </a>
    {% endif %}
    </div>
{% endblock content %}

templates/landing_page.html
{% extends 'base_generic.html' %}

{% block content %}
    <br />
    <h1> Welcome to Django CRM </h1>
    {% if request.user.is_authenticated %}
        <a href="{% url 'leads:leads_list' %}"> Take me to the leads </a>
    {% else %}
        <hr />
        <h3> Please login/signup to use the system </h1>
    {% endif %}
{% endblock content %}